pipeline {
  agent { docker { image 'mcr.microsoft.com/playwright:focal' } } 
  stages {  
    stage('test') {
      steps {
         sh 'npm install'
         sh 'npm test'
      }
    }
  }
}                                          
